sudo: required

language: python
python:
  - "2.7"

# notifications: # Lembrar de configurar depois!
  # slack:

services:
  - docker

before_install:
  - docker build -t presto docker/presto/ # Inicialização da imagem do PRESTO

install:
  - pip install python-coveralls colorlog
# The following command will install the latest version of a module and its
# dependencies from the Python Packaging Index

script:
  - docker run presto /bin/bash -c "python setup.py test"

after_success:
  - docker cp `docker ps -l -q`:/home/scientific/PRESTO/.coverage .coverage.docker
  # The docker cp utility copies the contents of SRC_PATH to the DEST_PATH

  - coverage combine
  # Coverage.py is a tool for measuring code coverage of Python programs.
  # It monitors your program, noting which parts of the code have been
  # executed, then analyzes the source to identify code that could have been
  # executed but was not

  # - coveralls  # Lembrar de configurar depois!
  # Coveralls is a web service to help you track your code coverage over time,
  # and ensure that all your new code is fully covered

  - docker tag padmec/presto
  # Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
